import {assets} from './assets.generated';
import {nextDate} from '../src/domain';
import type {User,Task} from '../src/domain';
const enc=new TextEncoder();
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value))),v=>v.toString(16).padStart(2,'0')).join('');}
const PBKDF2_ITERATIONS=100000;
function randomHex(bytes:number){return Array.from(crypto.getRandomValues(new Uint8Array(bytes)),v=>v.toString(16).padStart(2,'0')).join('');}
function hexToBytes(hex:string){const out=new Uint8Array(hex.length/2);for(let i=0;i<out.length;i++)out[i]=parseInt(hex.substr(i*2,2),16);return out;}
async function derivePassword(passwordValue:string,saltHex:string){const key=await crypto.subtle.importKey('raw',enc.encode(passwordValue),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:hexToBytes(saltHex),iterations:PBKDF2_ITERATIONS},key,256);return Array.from(new Uint8Array(bits),v=>v.toString(16).padStart(2,'0')).join('');}
function timingSafeEqual(a:string,b:string){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0;}
function json(data:unknown,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});}
function fail(message:string,status=400):never {throw Object.assign(new Error(message),{status});}
async function body(req:Request):Promise<Record<string,unknown>>{if(!req.headers.get('content-type')?.startsWith('application/json'))fail('Formato de solicitud inválido.',415);const reader=req.body?.getReader();if(!reader)fail('Datos inválidos.');let raw='';let size=0;const decoder=new TextDecoder();while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>16384){await reader.cancel();fail('La solicitud es demasiado grande.',413);}raw+=decoder.decode(part.value,{stream:true});}raw+=decoder.decode();try{const b=JSON.parse(raw);if(!b||typeof b!=='object'||Array.isArray(b))fail('Datos inválidos.');return b;}catch{fail('Datos inválidos.');}}
function text(b:Record<string,unknown>,key:string,max:number,required=true){const v=b[key];if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail('Revisá el campo '+key+'.');return v.trim();}
function username(b:Record<string,unknown>,key:string){const v=text(b,key,60).toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{1,58}[a-z0-9]$/.test(v))fail('El usuario debe tener 3 a 60 caracteres: minúsculas, números, puntos, guiones o guiones bajos.');return v;}
function password(b:Record<string,unknown>,key:string){const v=text(b,key,200);if(v.length<8)fail('La contraseña debe tener al menos 8 caracteres.');return v;}
async function actor(req:Request,env:Env){const t=req.headers.get('cookie')?.match(/(?:^|;\s*)home_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!t)fail('Ingresá con tu usuario y contraseña.',401);const u=await env.DB.prepare('SELECT u.id,u.name,u.role,u.active,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(await hash(t),new Date().toISOString()).first<User>();if(!u)fail('Tu sesión venció. Volvé a ingresar.',401);return u;}
async function taskData(b:Record<string,unknown>,env:Env){const title=text(b,'title',120),description=text(b,'description',2000,false),due=text(b,'due_date',10);if(!/^\d{4}-\d{2}-\d{2}$/.test(due)||!Number.isFinite(Date.parse(due))||new Date(due).toISOString().slice(0,10)!==due)fail('Elegí una fecha válida.');if(!['alta','media','baja'].includes(String(b.priority))||!['none','daily','weekly','monthly'].includes(String(b.recurrence)))fail('Prioridad o recurrencia inválida.');const assignee=b.assignee_id||null;if(assignee!==null&&(typeof assignee!=='string'||!await env.DB.prepare('SELECT id FROM users WHERE id=? AND active=1').bind(assignee).first()))fail('Responsable inválido.');return [title,description,due,String(b.priority),assignee,String(b.recurrence)];}
async function api(req:Request,env:Env,url:URL):Promise<Response>{
 const path=url.pathname,method=req.method;
 if(method!=='GET'&&req.headers.get('origin')!==url.origin)fail('Origen no permitido.',403);
 if(path==='/api/login'&&method==='POST'){const b=await body(req),name=username(b,'username'),pass=text(b,'password',200);const u=await env.DB.prepare('SELECT id,password_hash,password_salt FROM users WHERE username=? AND active=1').bind(name).first<{id:string;password_hash:string;password_salt:string}>();let ok=false;if(u)ok=timingSafeEqual(await derivePassword(pass,u.password_salt),u.password_hash);else await derivePassword(pass,randomHex(16));if(!u||!ok)fail('Usuario o contraseña incorrectos.',401);const t=token(),now=new Date();await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires_at<?').bind(now.toISOString()),env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await hash(t),u.id,new Date(now.getTime()+30*86400000).toISOString())]);return json({ok:true},200,{'Set-Cookie':`home_session=${t}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`});}
 const user=await actor(req,env);
 if(path==='/api/logout'&&method==='POST'){const t=req.headers.get('cookie')?.match(/home_session=([a-f0-9]{64})/)?.[1];if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(t)).run();return json({ok:true},200,{'Set-Cookie':'home_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});}
 if(path==='/api/account/password'&&method==='PUT'){const b=await body(req),current=text(b,'current_password',200),next=password(b,'new_password');const row=await env.DB.prepare('SELECT password_hash,password_salt FROM users WHERE id=?').bind(user.id).first<{password_hash:string;password_salt:string}>();if(!row||!timingSafeEqual(await derivePassword(current,row.password_salt),row.password_hash))fail('La contraseña actual no coincide.',401);const salt=randomHex(16),hashed=await derivePassword(next,salt),t=req.headers.get('cookie')?.match(/home_session=([a-f0-9]{64})/)?.[1];await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=?,password_salt=? WHERE id=?').bind(hashed,salt,user.id),env.DB.prepare('DELETE FROM sessions WHERE user_id=? AND token_hash!=?').bind(user.id,t?await hash(t):'')]);return json({ok:true});}
 if(path==='/api/state'&&method==='GET'){const [users,tasks]=await env.DB.batch([env.DB.prepare('SELECT id,name,role,active,username FROM users ORDER BY created_at'),env.DB.prepare("SELECT id,title,description,created_at,due_date,priority,assignee_id,status,completed_at,completed_by,recurrence,previous_id FROM tasks WHERE deleted_at IS NULL AND (? = 'admin' OR status = 'pending') ORDER BY due_date,created_at").bind(user.role)]);return json({user,users:users.results,tasks:tasks.results});}
 const match=path.match(/^\/api\/tasks\/([^/]+)(\/complete)?$/);
 if(match&&match[2]&&method==='POST'){const id=match[1],t=await env.DB.prepare('SELECT * FROM tasks WHERE id=? AND deleted_at IS NULL').bind(id).first<Task>();if(!t)fail('La tarea ya no está disponible.',404);if(t.status==='completed')return json({ok:true});const now=new Date().toISOString(),nonce=crypto.randomUUID();const statements=[env.DB.prepare("UPDATE tasks SET status='completed',completed_at=?,completed_by=?,completion_nonce=? WHERE id=? AND status='pending' AND deleted_at IS NULL AND due_date=? AND recurrence=?").bind(now,user.id,nonce,id,t.due_date,t.recurrence)];if(t.recurrence!=='none')statements.push(env.DB.prepare("INSERT OR IGNORE INTO tasks(id,title,description,created_at,due_date,priority,assignee_id,recurrence,previous_id) SELECT ?,title,description,?,?,priority,assignee_id,recurrence,id FROM tasks WHERE id=? AND completion_nonce=?").bind(crypto.randomUUID(),now,nextDate(t.due_date,t.recurrence),id,nonce));const results=await env.DB.batch(statements);if(!results[0].meta.changes){const current=await env.DB.prepare('SELECT status FROM tasks WHERE id=? AND deleted_at IS NULL').bind(id).first<{status:string}>();if(current?.status!=='completed')fail('La tarea cambió. Actualizá la lista y volvé a intentar.',409);}return json({ok:true});}
 if(user.role!=='admin')fail('Solo el administrador puede realizar este cambio.',403);
 if(path==='/api/tasks'&&method==='POST'){const data=await taskData(await body(req),env);await env.DB.prepare('INSERT INTO tasks(id,created_at,title,description,due_date,priority,assignee_id,recurrence) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),new Date().toISOString(),...data).run();return json({ok:true},201);}
 if(match&&!match[2]&&method==='PUT'){const data=await taskData(await body(req),env);const r=await env.DB.prepare("UPDATE tasks SET title=?,description=?,due_date=?,priority=?,assignee_id=?,recurrence=? WHERE id=? AND status='pending' AND deleted_at IS NULL").bind(...data,match[1]).run();if(!r.meta.changes)fail('La tarea ya fue completada o eliminada.',409);return json({ok:true});}
 if(match&&!match[2]&&method==='DELETE'){await env.DB.prepare("UPDATE tasks SET deleted_at=? WHERE id=? AND status='pending'").bind(new Date().toISOString(),match[1]).run();return json({ok:true});}
 if(path==='/api/members'&&method==='POST'){const b=await body(req),name=text(b,'name',60),name2=username(b,'username'),pass=password(b,'password');const existing=await env.DB.prepare('SELECT id FROM users WHERE username=?').bind(name2).first();if(existing)fail('Ese usuario ya existe.');const salt=randomHex(16),hashed=await derivePassword(pass,salt),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,name,role,username,password_hash,password_salt,created_at) VALUES(?,?,'member',?,?,?,?)").bind(id,name,name2,hashed,salt,new Date().toISOString()).run();return json({ok:true},201);}
 const member=path.match(/^\/api\/members\/([^/]+)\/(reset-password|revoke)$/);if(member&&method==='POST'){if(member[1]===user.id)fail('No podés modificar tu propio acceso desde acá.');const target=await env.DB.prepare("SELECT id FROM users WHERE id=? AND role='member'").bind(member[1]).first();if(!target)fail('Miembro no encontrado.',404);if(member[2]==='reset-password'){const pass=password(await body(req),'password'),salt=randomHex(16),hashed=await derivePassword(pass,salt);await env.DB.batch([env.DB.prepare('UPDATE users SET active=1,password_hash=?,password_salt=? WHERE id=?').bind(hashed,salt,member[1]),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(member[1])]);return json({ok:true});}await env.DB.batch([env.DB.prepare('UPDATE users SET active=0 WHERE id=?').bind(member[1]),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(member[1])]);return json({ok:true});}
 return json({error:'Ruta no encontrada.'},404);
}
export default {async fetch(req:Request,env:Env):Promise<Response>{const url=new URL(req.url);let response:Response;try{if(url.pathname.startsWith('/api/')){if(Number(req.headers.get('content-length')||0)>16384)fail('Solicitud demasiado grande.',413);response=await api(req,env,url);}else{const asset=assets[url.pathname==='/'?'/index.html':url.pathname];response=asset?new Response(asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache'}}):new Response('No encontrado',{status:404});}}catch(e){const err=e as Error&{status?:number};if(!err.status)console.error(JSON.stringify({event:'request_error',path:url.pathname,message:err.message}));response=json({error:err.status?err.message:'No pudimos guardar el cambio. Volvé a intentar.'},err.status||500);}response.headers.set('X-Content-Type-Options','nosniff');response.headers.set('Referrer-Policy','no-referrer');response.headers.set('X-Frame-Options','DENY');response.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");return response;}} satisfies ExportedHandler<Env>;
